SUPABASE_URL = "https://ruqxylaobelvcckinbtw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cXh5bGFvYmVsdmNja2luYnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3OTc2MDAsImV4cCI6MjA5MzM3MzYwMH0.kf0IEJLsfx95MV3REs93UO2GeaeIOhxac16xoVZL25M"
